### ISSUE TITLE
Consider new repo name and purpose

### ISSUE THREAD

**Issue by redhatrises** [GoComply/fedramp#4]
Rather than being about fedramp only, should this repo be called (or a new one created) "ssp-generator" or something like that? Seems like we can generate more than just FedRAMP SSPs and which would be great for us to do.

**Comment by isimluk** [comment]
Not at the moment. It would increase scope too early.

Looking at https://github.com/usnistgov/OSCAL it seems that last couple of months of development have been increasingly tightly coupled with FedRAMP. Moreover, FedRAMP stuff published at https://github.com/GSA/fedramp-automation is unparalleled by anything other.

Renaming is easy and can be done later on. Code is structured well for such extension. Anything fedramp related is encapsulated in separate module (see https://github.com/GoComply/fedramp/tree/master/pkg).

Overall, I would argue less is more in the these early stages.
